services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=employee_db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  employee:
    image: 'employee:latest'
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/employee_db'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=root'
    ports:
      - '8080:8080'